#######################################################################
# This script plots results for r generated by 
# Simulate_Sanger_Barcode.R, Simulate_GTseq.R and Simulate_GTseq_rmCTSA.R
# showing RMSE for all k and CIs for only k = 10
# The plotting is a bit hacky - some magic numbers (e.g line 131) etc. 
#######################################################################
rm(list = ls())
require(RColorBrewer)
PDF = T
if(PDF){pdf(file = '../Plots/GTseq_vs_Sanger_Barcode_Sim.pdf', width = 8, height = 7)}
par(mfrow = c(3,5), mar = c(0,0,0,0), oma = c(4,4,2,2), family = 'serif', pty = 'm')

# Sanger
palettes = c("frenchGuiana" = 'YlGn', "columbia" = 'YlOrRd', "senegal" = 'YlGnBu')
Countries = names(palettes)
load(sprintf('../RData/Sanger_Amplicon_SimResults_%s.Rdata', Countries[1]))
k10ind = which(grepl("k=10 ", names(PPair_results)))

for(i in k10ind){
  
  for(Country in Countries){
    
    load(sprintf('../RData/Sanger_Amplicon_SimResults_%s.Rdata', Country))
    
    rs = colnames(RMSEk_results)
    cols_rs = sapply(brewer.pal(length(rs)+2, palettes[Country])[-(1:2)], 
                     function(x)adjustcolor(x,alpha.f = 0.75))
    
    # Extract parameter values used to generate the data
    krchr = unlist(strsplit(names(PPair_results)[i], split = ' '))
    r = as.numeric(gsub('r=', '', krchr[2]))
    if(krchr[1] != "k=10"){stop("Incorrect k")}
    
    # Extract results
    X = PPair_results[[i]]
    rCIs = sapply(X, function(x)x[,'r'])
    rest = rCIs['rkhat',]
    
    # Order results
    Order = sort.int(rest, index.return = T)$ix
    ADD = ifelse(Country == Countries[1], FALSE, TRUE)
    
    # Plot results
    if(Country == Countries[1]){
      plot(NULL, pch = 20, ylim = c(0,1), xlim = c(1,length(rest)), 
           xaxt = 'n', yaxt = 'n', panel.first = grid())
    }
    polygon(x = c(1:length(rest), length(rest):1), 
            y = c(rCIs['2.5%', Order], rev(rCIs['97.5%', Order])),
            col = tail(cols_rs,2)[1], border = NA)
    lines(rest[Order], col = 'white')
    abline(h = r, col = 'black')
    
    # Add title
    if(i == k10ind[1]){
      axis(side = 2, las = 1)
      title(main = 'Sanger barcode', line = -6)}
  } 
}


# GTseq w & w/o CTSA
palettes = c("frenchGuiana" = 'YlGn', "columbia" = 'YlOrRd', "senegal" = 'YlGnBu', 'mali' = 'PuRd')
Countries = names(palettes)

for(rmCTSA in c(T,F)){
  
  if(rmCTSA){
    load(sprintf('../RData/GTseq_rmCTSA_Amplicon_SimResults_%s.Rdata', Countries[1]))
  } else {
    load(sprintf('../RData/GTseq_Amplicon_SimResults_%s.Rdata', Countries[1]))
  }
  
  k10ind = which(grepl("k=10 ", names(PPair_results)))
  colour_store = c()
  
  for(i in k10ind){
    
    for(Country in Countries){
      
      if(rmCTSA){
        load(sprintf('../RData/GTseq_rmCTSA_Amplicon_SimResults_%s.Rdata', Country))
      } else {
        load(sprintf('../RData/GTseq_Amplicon_SimResults_%s.Rdata', Country))
      }
      
      rs = colnames(RMSEk_results)
      cols_rs = sapply(brewer.pal(length(rs)+2, palettes[Country])[-(1:2)], 
                       function(x)adjustcolor(x,alpha.f = 0.75))
      
      # Extract parameter values used to generate the data
      krchr = unlist(strsplit(names(PPair_results)[i], split = ' '))
      r = as.numeric(gsub('r=', '', krchr[2]))
      if(krchr[1] != "k=10"){stop("Incorrect k")}
      
      # Extract results
      X = PPair_results[[i]]
      rCIs = sapply(X, function(x)x[,'r'])
      rest = rCIs['rkhat',]
      
      # Order results
      Order = sort.int(rest, index.return = T)$ix
      ADD = ifelse(Country == Countries[1], FALSE, TRUE)
      
      # Plot results
      if(Country == Countries[1]){
        plot(NULL, pch = 20, ylim = c(0,1), xlim = c(1,length(rest)), 
             xaxt = 'n', yaxt = 'n', panel.first = grid())
      }
      polygon(x = c(1:length(rest), length(rest):1), 
              y = c(rCIs['2.5%', Order], rev(rCIs['97.5%', Order])),
              col = tail(cols_rs,2)[1], border = NA)
      lines(rest[Order], col = 'white')
      abline(h = r, col = 'black')
      
      # Add axes
      if(i == k10ind[1] & rmCTSA){
        title(main = 'GTseq panel exc. CTSA', line = -6)
      }
      if(i == k10ind[1] & !rmCTSA){
        title(main = 'GTseq panel inc. CTSA', line = -6)
        axis(side = 2, las = 1)
        axis(side = 1)
        title(ylab = expression("Relatedness,"~italic(r)), 
              xlab = 'Sample pair index', line = 2.5, outer = T, cex = 2, adj = 0.05)
        legend('top', lty = c(1,NA), bty = 'n', 
               legend = c(expression('Data generating'~italic(r)), krchr[1]), 
               inset = 0.05)
      }
      
      colour_store = c(colour_store, tail(cols_rs,2)[1])
      
    } 
  }
}

# Add country legend: 
legend('bottom', bty = 'n', legend = Countries, cex = 1.25,
       fill = colour_store, inset = 0.01)










# Plot RMSE
par(mfrow = c(3,length(Countries)), mar = c(4,5,2,2), oma = rep(0,4), pty = 's')

for(Country in Countries[1:3]){
  
  load(sprintf('../RData/Sanger_Amplicon_SimResults_%s.Rdata', Country))
  
  rs = colnames(RMSEk_results)
  ks = rownames(RMSEk_results)
  cols_rs = brewer.pal(length(rs)+2, palettes[Country])[-(1:2)]
  cols_ks = brewer.pal(length(ks)+2, palettes[Country])[-(1:2)]
  
  # Error in the r parameter
  matplot(t(RMSEr_results), type = 'b', pch = 20, lty = 1, col = cols_ks, panel.fist = grid(), 
          ylab = expression('RMSE: relatedness,'~italic(r)), 
          xlab = expression('Relatedness,'~italic(r)), 
          xaxt = 'n', bty = 'n', ylim = c(0,0.16), main = Country)
  axis(side = 1, at = 1:length(rs), labels = rs)
  legend('bottom', bty = 'n', lty = 1, pch = 20, col = cols_ks, inset = 0.05, cex = 0.75, 
         legend = ks, title = expression('Switch rate parameter,'~italic(k)))
}
# Add null plot to end of Sanger since missing mali
plot(NULL, xlim = c(0,1), ylim = c(0,1), bty = 'n', xaxt = 'n', yaxt = 'n', ylab = '', xlab = '')


for(rmCTSA in c(T,F)){
  
  for(Country in Countries){
    
    if(rmCTSA){
      load(sprintf('../RData/GTseq_rmCTSA_Amplicon_SimResults_%s.Rdata', Countries[1]))
    } else {
      load(sprintf('../RData/GTseq_Amplicon_SimResults_%s.Rdata', Countries[1]))
    }
    
    rs = colnames(RMSEk_results)
    ks = rownames(RMSEk_results)
    cols_rs = brewer.pal(length(rs)+2, palettes[Country])[-(1:2)]
    cols_ks = brewer.pal(length(ks)+2, palettes[Country])[-(1:2)]
    
    # Error in the r parameter
    matplot(t(RMSEr_results), type = 'b', pch = 20, lty = 1, col = cols_ks, panel.fist = grid(), 
            ylab = expression('RMSE: relatedness,'~italic(r)), 
            xlab = expression('Relatedness,'~italic(r)), 
            xaxt = 'n', bty = 'n', ylim = c(0,0.16), main = Country)
    axis(side = 1, at = 1:length(rs), labels = rs)
    legend('bottom', bty = 'n', lty = 1, pch = 20, col = cols_ks, inset = 0.05, cex = 0.75, 
           legend = ks, title = expression('Switch rate parameter,'~italic(k)))
  }
  
}


if(PDF){dev.off()}


