###################################################################
# This script plots results generated by Simulate_Sanger_Barcode.R
# minimum k ought probably be 2
###################################################################
rm(list = ls())
require(RColorBrewer)
display.brewer.all(colorblindFriendly = T)
palettes = c("Senegal" = 'YlGnBu', "Columbia" = 'YlOrRd', "FrenchGuiana" = 'YlGn')
Countries = names(palettes)
PDF = F
if(PDF){pdf(file = '../Plots/Sanger_Barcode_Sim.pdf', width = 8, height = 7)}
par(family = 'serif', pty = 'm')



for(Country in Countries){

  load(sprintf('../RData/Sanger_Amplicon_SimResults_%s.Rdata', Country))

  rs = colnames(RMSEk_results)
  ks = rownames(RMSEk_results)
  cols_rs = brewer.pal(length(rs)+2, palettes[Country])[-(1:2)]
  cols_ks = brewer.pal(length(ks)+2, palettes[Country])[-(1:2)]
  
  # Confidence intervals around r
  par(mfcol = c(4,5), mar = c(0,0,0,0), oma = c(4,4,2,2))
  coverage = array(dim = c(length(PPair_results),2), dimnames = list(names(PPair_results),c('k','r')))
  for(i in 1:length(PPair_results)){
    
    # Extract parameter values used to generate the data
    krchr = unlist(strsplit(names(PPair_results)[i], split = ' '))
    k = as.numeric(gsub('k=', '', krchr[1]))
    r = as.numeric(gsub('r=', '', krchr[2]))
    
    # Extract results
    X = PPair_results[[i]]
    rCIs = sapply(X, function(x)x[,'r'])
    rest = rCIs['rkhat',]
    
    # Order results
    Order = sort.int(rest, index.return = T)$ix
    
    # Plot results
    plot(NULL, pch = 20, ylim = c(0,1), xlim = c(1,length(rest)), 
         xaxt = 'n', yaxt = 'n', panel.first = grid())
    polygon(x = c(1:length(rest), length(rest):1), 
            y = c(rCIs['2.5%', Order], rev(rCIs['97.5%', Order])),
            col = tail(cols_rs,2)[1], border = NA)
    lines(rest[Order], col = 'white')
    abline(h = r, col = 'black')
    
    # Add axes
    if(i == 4){
      axis(side = 2, las = 1)
      axis(side = 1)
      title(ylab = expression("Relatedness,"~italic(r)), 
            xlab = 'Sample pair index', line = 2.5, outer = T, cex = 2, adj = 0.05)
      legend('top', lty = 1, bty = 'n', legend = expression(italic(r)), 
             title = 'Data generating')
    }
    
    # Extract coverage
    coverage[i,'r'] = mean(apply(rCIs, 2, function(x) x[1] >= x[2] & x[1] <= x[3])) 
    
    # Annotate with parameter values
    if(i <= 12){
      mtext(side = 3, text = bquote(italic(k) ==.(k)~italic(r)==.(r)), line = -2)
    } else {
      mtext(side = 1, text = bquote(italic(k) ==.(k)~italic(r)==.(r)), line = -2)
    }
  } 
  
  
  # Confidence intervals around k (log scale)
  par(mfrow = c(5,4), mar = c(0,0,0,0), oma = c(4,4,2,2))
  for(i in 1:length(PPair_results)){
    
    # Extract parameter values used to generate the data
    krchr = unlist(strsplit(names(PPair_results)[i], split = ' '))
    k = as.numeric(gsub('k=', '', krchr[1]))
    r = as.numeric(gsub('r=', '', krchr[2]))
    
    # Extract results
    X = PPair_results[[i]]
    kCIs = sapply(X, function(x)x[,'k'])
    kest = kCIs['rkhat',]
    
    # Order results
    Order = sort.int(kest, index.return = T)$ix
    
    # Plot results
    plot(NULL, pch = 20, ylim = c(0,log(max(kCIs))), xlim = c(1,length(kest)), 
         xaxt = 'n', yaxt = 'n', panel.first = grid())
    polygon(x = c(1:length(kest), length(kest):1), 
            y = log(c(kCIs['2.5%', Order], rev(kCIs['97.5%', Order]))),
            col = tail(cols_rs,2)[1], border = NA)
    lines(log(kest[Order]), col = 'white')
    abline(h = log(k), col = 'black')
    
    # Add axes
    if(i == 17){
      axis(side = 2, las = 1)
      axis(side = 1)
      title(ylab = expression(Log[e]~"switch rate parameter,"~italic(k)), 
            xlab = 'Sample pair index', line = 2.5, outer = T, cex = 2, adj = 0.05)
      legend('top', lty = 1, bty = 'n', legend = expression(italic(k)), 
             title = 'Data generating')
    }
    
    # Extract coverage
    coverage[i,'k'] = mean(apply(kCIs, 2, function(x) x[1] >= x[2] & x[1] <= x[3])) 
    
    #Annotate with parameter values
    mtext(side = 3, text = bquote(italic(k) ==.(k)~italic(r)==.(r)), line = -2)
  } 

  # Check coverage 
  any(coverage < 0.95)
}

# Plot RMSE
par(mfcol = c(2,length(Countries)), mar = c(4,5,2,2), oma = rep(0,4), pty = 's')
for(Country in Countries){
  
  load(sprintf('../RData/Sanger_Amplicon_SimResults_%s.Rdata', Country))
  
  rs = colnames(RMSEk_results)
  ks = rownames(RMSEk_results)
  cols_rs = brewer.pal(length(rs)+2, palettes[Country])[-(1:2)]
  cols_ks = brewer.pal(length(ks)+2, palettes[Country])[-(1:2)]
  
  
  # Error in the r parameter
  matplot(t(RMSEr_results), type = 'b', pch = 20, lty = 1, col = cols_ks, panel.fist = grid(), 
          ylab = expression('RMSE: relatedness,'~italic(r)), 
          xlab = expression('Relatedness,'~italic(r)), 
          xaxt = 'n', bty = 'n', ylim = c(0,0.16), main = Country)
  axis(side = 1, at = 1:length(rs), labels = rs)
  legend('bottom', bty = 'n', lty = 1, pch = 20, col = cols_ks, inset = 0.05, cex = 0.75, 
         legend = ks, title = expression('Switch rate parameter,'~italic(k)))
  
  
  # Error in the k parameter
  matplot(RMSEk_results, type = 'b', pch = 20, lty = 1, col = cols_rs, panel.fist = grid(),  
          ylab = expression('RMSE: switch rate parameter,'~italic(k)),
          xlab = expression('Switch rate parameter,'~italic(k)), 
          xaxt = 'n', bty = 'n', ylim = c(0,20000), main = Country)
  axis(side = 1, at = 1:length(ks), labels = ks)
  legend('topleft', bty = 'n', lty = 1, pch = 20, col = cols_rs, inset = 0.01, cex = 0.75, 
         legend = rs, title = expression('Relatedness,'~italic(r)))

}

if(PDF){dev.off()}


